# -*- coding: utf-8 -*-
"""
Language dictionaries for TSC Editor+.
"""

LANGS = {
    'en': {
        'window_title': 'TSC Editor+',
        'file_menu': 'File',
        'open_tsc': 'Open .tsc...',
        'open_project': 'Open .cstsc project...',
        'open_folder': 'Open project folder...',
        'delete_from_list': 'Delete loaded TSC from this list',
        'delete_all_from_list': 'Delete all TSCs from this list',
        'export_tsc': 'Export .tsc...',
        'save_project': 'Save project .cstsc...',
        'settings': 'Settings...',
        'exit': 'Exit',
        'edit_menu': 'Edit',
        'undo': 'Undo',
        'redo': 'Redo',
        'search_tab': 'Search',
        'check_syntax': 'Check Syntax',
        'smart_replace': 'Smart Replace Special Characters',
        'view_menu': 'View',
        'font_size': 'Font size...',
        'hex_dump': 'Hex dump of current file...',
        'show_history': 'Show History',
        'see_quick_docs': 'See Quick Docs',
        'edit_custom_cmds': 'Edit Custom Commands...',
        'font_submenu': 'Font',
        'run_menu': 'Run',
        'find_doukutsu': 'Find doukutsu.exe...',
        'test_game': 'Test (F5)',
        'help_menu': 'Help',
        'about': 'About...',
        'search_label': 'Search file:',
        'clear_btn': 'X',
        'status_ready': 'Ready',
        'open_project_dialog_title': 'Open .cstsc project',
        'save_project_dialog_title': 'Save project',
        'export_tsc_dialog_title': 'Save .tsc file',
        'load_folder_title': 'Select folder with .tsc files',
        'hex_info': 'No data',
        'hex_window_title': 'Hex dump (first 512 bytes)',
        'settings_window_title': 'Settings',
        'auto_save_label': 'Auto-save project (.cstsc) every 6 minutes',
        'dark_theme_label': 'Dark theme',
        'language_label': 'Language:',
        'default_font_label': 'Default font:',
        'apply_btn': 'Apply',
        'close_btn': 'Close',
        'cmd_info_title': 'Info',
        'cmd_not_found': 'No TSC command at cursor.',
        'cmd_unrecognized': 'Command format not recognized.',
        'cmd_unknown': 'No documentation for',
        'music_id': 'Music ID',
        'direction': 'Direction',
        'empty_warning': 'The text is empty. Save anyway?',
        'overwrite_msg': 'Overwrite',
        'overwrite_question': 'Overwrite',
        'export_success': 'File saved successfully.',
        'project_saved': 'Project saved in UTF-8.',
        'load_error': 'Could not load file',
        'save_error': 'Could not save file',
        'search_not_found': 'No more matches found.',
        'search_back_not_found': 'No more matches backwards.',
        'replace_all_count': ' replacements performed.',
        'no_file_warning': 'No file loaded. Load or save a .tsc first.',
        'save_before_test': 'Save changes before running?',
        'exe_not_found': 'Could not find doukutsu.exe',
        'game_launched': 'Game launched',
        'lines': 'Lines',
        'chars': 'Chars',
        'history': 'History',
        'copy': 'Copy',
        'paste': 'Paste',
        'cut': 'Cut',
        'count_chars': 'Count Characters',
        'count_chars_face': 'Count Characters (Face)',
        'count_normal_title': 'Character count (Normal)',
        'count_face_title': 'Character count (Face)',
        'fits': 'This text fits correctly in the message box',
        'not_fits': 'This text may NOT fit correctly in the message box',
        'limit': 'Limit',
        'quick_docs': 'Quick Docs',
        'command': 'Command',
        'syntax': 'Syntax',
        'description': 'Description',
        'details': 'Script Details',
        'face_name': 'Face',
        'music_name': 'Music',
        'confirm': 'Confirm',
        'backup_warning': 'It is recommended to make a backup of this TSC file before proceeding.\nThis action cannot be undone (except via Undo).',
        'done': 'Done',
        'no_changes': 'No changes',
        'smart_replace_title': 'Smart Replace Special Characters',
        'option_nn': "Replace 'ñÑ' with 'nN'",
        'option_accents': 'Remove accents (áéíóúüÁÉÍÓÚÜ) → aeiouuAEIOUU',
        'option_symbols': 'Remove rare symbols (¡¿)',
        'option_all': 'All of the above',
        'syntax_errors': 'Syntax Errors',
        'syntax_errors_found': 'Syntax errors found. Save anyway?',
        'syntax_no_errors': 'No syntax errors found.',
        'syntax_error_window_title': 'Syntax Check',
        'auto_save_notification': 'Project auto-saved',
        'find': 'Find',
        'replace': 'Replace',
        'replace_all': 'Replace All',
        'find_next': 'Find Next',
        'find_prev': 'Find Previous',
        'case_sensitive': 'Case sensitive',
        'whole_word': 'Whole word',
        'search_term': 'Search term:',
        'replace_term': 'Replace with:',
        'edit_custom_cmds_title': 'Edit Custom Commands',
        'custom_cmd_name': 'Command name (without <):',
        'custom_cmd_desc': 'Description:',
        'custom_cmd_args': 'Number of arguments (0-4):',
        'search_docs': 'Search command...',
        'tsc_commands': 'Show command info',
        'custom_cmd_syntax': 'Custom Command Syntax...',
        'cmd_syntax_window_title': 'Command Syntax Analyzer',
        'cmd_input_label': 'Command line (e.g. <CMU0000 or <FAC0001):',
        'parse_button': 'Analyze',
        'syntax_result_title': 'Analysis result:',
        'syntax_error_purpose': 'Force syntax error (invalid command)',
        'clear_button': 'Clear',
        'command_type': 'Command',
        'id_type': 'ID',
        'error_type': 'Error',
        'command_color': 'Blue',
        'id_color': 'Pink',
        'error_color': 'Red',
        'unknown_command': 'Unknown command',
        'missing_param': 'Missing parameter',
        'invalid_param': 'Invalid parameter (must be 4 digits)',
        'extra_text': 'Extra text after command',
        'command_header': 'Command name',
        'id_header': 'ID/Parameter',
        'error_header': 'Error description',
        'customize_command_colors': 'Customize Command Colors...',
        'cmd_colors_title': 'Command Color Customization',
        'cmd_color_instruction': 'Select a command and assign a color:',
        'cmd_list': 'Command',
        'current_color': 'Current Color',
        'assign_color': 'Assign Color',
        'color_blue': 'Blue (default)',
        'color_pink': 'Pink (like ID)',
        'color_red': 'Red (error)',
        'color_reset': 'Reset to default',
        'unsaved_title': 'Unsaved Changes',
        'unsaved_message': 'There are unsaved changes in the current file.\n\nDo you want to save them before opening {}?\n\nYes = Save and continue\nNo = Discard changes and continue\nCancel = Do not change file',
        'unsaved_tab_title': 'Unsaved Changes',
        'unsaved_tab_message': 'There are unsaved changes in "{}".\nDo you want to save them before closing?',
        'face_version_title': 'Select version',
        'face_version_question': 'Show face ID {} from which version?',
        'face_version_freeware': 'Freeware',
        'face_version_steam': 'Steam',
        'face_version_cancel': 'Cancel',
        'face_view_title': 'Show face',
        'face_view_question': 'Show face image for ID {}?\n(You can choose version later)',
        'ai_assistant': "AI Assistant",
        'hints': [
            "Did you know that animated faces <FAC01XX>, <FAC10XX>, <FAC11XX> are exclusive to Switch?",
            "Did you know that TSC files on Switch are plain text?",
            "Be careful not to write too much or you'll exceed the text box! Select your text, right-click and use the character counter.",
            "Place an event with #. Remember, stay organized with IDs.",
            "Pro tip: Use the keyboard.",
            "Your text not showing in-game? Maybe you used '¿¡'. Right-click and remove those characters with one click.",
            "Be careful when putting comments in these files; the game is touchy and may get confused.",
            "Use another editor every now and then.",
            "Pro tip: Use the mouse or touchpad.",
            "Backup your TSC files; one wrong step and the game crashes.",
            "Before editing, you must configure.",
            "Press F5 to test quickly.",
            "TSC programming language is so simple it's almost a joke (but don't think it's a piece of cake).",
            "Don't know what a command does and too lazy to check docs? Right-click and see a summary.",
            "If your TSC opens as 'hhxxjxnjxb#=hh+¨shswhh', change the cipher and you'll be able to read it."
        ]
    },
    'es': {
        'window_title': 'TSC Editor+',
        'file_menu': 'Archivo',
        'open_tsc': 'Abrir .tsc...',
        'open_project': 'Abrir proyecto .cstsc...',
        'open_folder': 'Abrir carpeta de proyectos...',
        'delete_from_list': 'Eliminar TSC cargado de esta lista',
        'delete_all_from_list': 'Eliminar todos los TSC de esta lista',
        'export_tsc': 'Exportar .tsc...',
        'save_project': 'Guardar proyecto .cstsc...',
        'settings': 'Configuración...',
        'exit': 'Salir',
        'edit_menu': 'Editar',
        'undo': 'Deshacer',
        'redo': 'Rehacer',
        'search_tab': 'Buscar',
        'check_syntax': 'Verificar sintaxis',
        'smart_replace': 'Reemplazo inteligente de caracteres especiales',
        'view_menu': 'Ver',
        'font_size': 'Tamaño de fuente...',
        'hex_dump': 'Ver hexadecimal del archivo actual...',
        'show_history': 'Mostrar historial',
        'see_quick_docs': 'Ver documentación rápida',
        'edit_custom_cmds': 'Editar comandos personalizados...',
        'font_submenu': 'Fuente',
        'run_menu': 'Ejecutar',
        'find_doukutsu': 'Buscar doukutsu.exe...',
        'test_game': 'Probar (F5)',
        'help_menu': 'Ayuda',
        'about': 'Acerca de...',
        'search_label': 'Buscar archivo:',
        'clear_btn': 'X',
        'status_ready': 'Listo',
        'open_project_dialog_title': 'Abrir proyecto .cstsc',
        'save_project_dialog_title': 'Guardar proyecto',
        'export_tsc_dialog_title': 'Guardar archivo .tsc',
        'load_folder_title': 'Seleccionar carpeta con archivos .tsc',
        'hex_info': 'Sin datos',
        'hex_window_title': 'Vista hexadecimal (primeros 512 bytes)',
        'settings_window_title': 'Configuración',
        'auto_save_label': 'Auto-guardar proyecto (.cstsc) cada 6 minutos',
        'dark_theme_label': 'Tema oscuro',
        'language_label': 'Idioma:',
        'default_font_label': 'Fuente predeterminada:',
        'apply_btn': 'Aplicar',
        'close_btn': 'Cerrar',
        'cmd_info_title': 'Información',
        'cmd_not_found': 'No hay un comando TSC en esta posición.',
        'cmd_unrecognized': 'Formato de comando no reconocido.',
        'cmd_unknown': 'No hay documentación para',
        'music_id': 'ID de música',
        'direction': 'Dirección',
        'empty_warning': 'El texto está vacío. ¿Guardar de todos modos?',
        'overwrite_msg': 'Sobrescribir',
        'overwrite_question': '¿Sobrescribir',
        'export_success': 'Archivo guardado correctamente.',
        'project_saved': 'Proyecto guardado en UTF-8.',
        'load_error': 'No se pudo cargar el archivo',
        'save_error': 'No se pudo guardar',
        'search_not_found': 'No se encontró más texto.',
        'search_back_not_found': 'No se encontró texto hacia atrás.',
        'replace_all_count': ' reemplazos realizados.',
        'no_file_warning': 'No hay archivo cargado. Cargue o guarde un .tsc primero.',
        'save_before_test': '¿Guardar cambios antes de ejecutar?',
        'exe_not_found': 'No se encontró doukutsu.exe',
        'game_launched': 'Juego lanzado',
        'lines': 'Líneas',
        'chars': 'Caracteres',
        'history': 'Historial',
        'copy': 'Copiar',
        'paste': 'Pegar',
        'cut': 'Cortar',
        'count_chars': 'Contar caracteres',
        'count_chars_face': 'Contar caracteres (cara)',
        'count_normal_title': 'Conteo de caracteres (Normal)',
        'count_face_title': 'Conteo de caracteres (Cara)',
        'fits': 'Este mensaje puede caber correctamente en la caja de diálogo',
        'not_fits': 'Este mensaje quizá NO pueda caber correctamente en la caja de diálogo',
        'limit': 'Límite',
        'quick_docs': 'Documentación rápida',
        'command': 'Comando',
        'syntax': 'Sintaxis',
        'description': 'Descripción',
        'details': 'Detalles del script',
        'face_name': 'Cara',
        'music_name': 'Música',
        'confirm': 'Confirmar',
        'backup_warning': 'Se recomienda hacer una copia de seguridad de este archivo TSC antes de continuar.\nEsta acción no se puede deshacer (excepto mediante Deshacer).',
        'done': 'Hecho',
        'no_changes': 'Sin cambios',
        'smart_replace_title': 'Reemplazo inteligente de caracteres especiales',
        'option_nn': "Reemplazar 'ñÑ' por 'nN'",
        'option_accents': 'Eliminar acentos (áéíóúüÁÉÍÓÚÜ) → aeiouuAEIOUU',
        'option_symbols': 'Eliminar símbolos raros (¡¿)',
        'option_all': 'Todo lo anterior',
        'syntax_errors': 'Errores de sintaxis',
        'syntax_errors_found': 'Se encontraron errores de sintaxis. ¿Guardar de todos modos?',
        'syntax_no_errors': 'No se encontraron errores de sintaxis.',
        'syntax_error_window_title': 'Verificación de sintaxis',
        'auto_save_notification': 'Proyecto auto-guardado',
        'find': 'Buscar',
        'replace': 'Reemplazar',
        'replace_all': 'Reemplazar todo',
        'find_next': 'Buscar siguiente',
        'find_prev': 'Buscar anterior',
        'case_sensitive': 'Mayúsculas/minúsculas',
        'whole_word': 'Palabra completa',
        'search_term': 'Término a buscar:',
        'replace_term': 'Reemplazar con:',
        'edit_custom_cmds_title': 'Editar comandos personalizados',
        'custom_cmd_name': 'Nombre del comando (sin <):',
        'custom_cmd_desc': 'Descripción:',
        'custom_cmd_args': 'Número de argumentos (0-4):',
        'search_docs': 'Buscar comando...',
        'tsc_commands': 'Mostrar información del comando',
        'custom_cmd_syntax': 'Sintaxis de comando personalizado...',
        'cmd_syntax_window_title': 'Analizador de sintaxis de comandos',
        'cmd_input_label': 'Línea de comando (ej. <CMU0000 o <FAC0001):',
        'parse_button': 'Analizar',
        'syntax_result_title': 'Resultado del análisis:',
        'syntax_error_purpose': 'Forzar error de sintaxis (comando inválido)',
        'clear_button': 'Limpiar',
        'command_type': 'Comando',
        'id_type': 'ID',
        'error_type': 'Error',
        'command_color': 'Azul',
        'id_color': 'Rosa',
        'error_color': 'Rojo',
        'unknown_command': 'Comando desconocido',
        'missing_param': 'Parámetro faltante',
        'invalid_param': 'Parámetro inválido (deben ser 4 dígitos)',
        'extra_text': 'Texto extra después del comando',
        'command_header': 'Nombre del comando',
        'id_header': 'ID/Parámetro',
        'error_header': 'Descripción del error',
        'customize_command_colors': 'Personalizar colores de comandos...',
        'cmd_colors_title': 'Personalización de colores de comandos',
        'cmd_color_instruction': 'Selecciona un comando y asígnale un color:',
        'cmd_list': 'Comando',
        'current_color': 'Color actual',
        'assign_color': 'Asignar color',
        'color_blue': 'Azul (por defecto)',
        'color_pink': 'Rosa (como ID)',
        'color_red': 'Rojo (error)',
        'color_reset': 'Restablecer a por defecto',
        'unsaved_title': 'Cambios sin guardar',
        'unsaved_message': 'Hay cambios sin guardar en el archivo actual.\n\n¿Desea guardarlos antes de abrir {}?\n\nSí = Guardar y continuar\nNo = Descartar cambios y continuar\nCancelar = No cambiar de archivo',
        'unsaved_tab_title': 'Cambios sin guardar',
        'unsaved_tab_message': 'Hay cambios sin guardar en "{}".\n¿Desea guardarlos antes de cerrar?',
        'face_version_title': 'Seleccionar versión',
        'face_version_question': '¿Mostrar cara ID {} de qué versión?',
        'face_version_freeware': 'Freeware',
        'face_version_steam': 'Steam',
        'face_version_cancel': 'Cancelar',
        'face_view_title': 'Ver cara',
        'face_view_question': '¿Mostrar imagen de la cara {}?\n(Puedes elegir versión después)',
        'ai_assistant': "Asistente IA",
        'hints': [
            "¿Sabías que las caras animadas <FAC01XX>, <FAC10XX>, <FAC11XX> son exclusivas de Switch?",
            "¿Sabías que los TSC en Switch son solo texto plano?",
            "¡Ten cuidado escribiendo de más o te saldrás de la caja de texto! Selecciona tu texto, haz clic derecho y usa el contador de caracteres.",
            "Coloca un evento con #. Recuerda, sé organizado con los IDs.",
            "Pro tip: Usa el teclado.",
            "Tu texto no se muestra en el juego, posiblemente usaste '¿¡'. Haz clic derecho y elimina esos caracteres con un clic.",
            "Ten cuidado al poner comentarios en estos archivos; el juego es malpensado y se puede confundir.",
            "Usa otro editor de vez en cuando.",
            "Pro tip: Usa el mouse o touchpad.",
            "Haz respaldos de tus TSC; un paso en falso y el juego explota.",
            "Antes de editar, debes configurar.",
            "Pulsa F5 para testear rápidamente.",
            "El lenguaje de programación TSC es tan sencillo que parece chiste (pero no te creas que es pan comido).",
            "¿No sabes qué hace X comando y te da flojera ir a la documentación? Haz clic derecho y verás un resumen de ello.",
            "Si tu TSC abre así 'hhxxjxnjxb#=hh+¨shswhh', cambia el cifrado y podrás leerlo."
        ]
    },
    'jp': {
        'window_title': 'TSC Editor+',
        'file_menu': 'ファイル',
        'open_tsc': '.tscを開く...',
        'open_project': '.cstscプロジェクトを開く...',
        'open_folder': 'プロジェクトフォルダを開く...',
        'delete_from_list': 'ロードしたTSCをこのリストから削除',
        'delete_all_from_list': 'すべてのTSCをリストから削除',
        'export_tsc': '.tscにエクスポート...',
        'save_project': 'プロジェクトを保存.cstsc...',
        'settings': '設定...',
        'exit': '終了',
        'edit_menu': '編集',
        'undo': '元に戻す',
        'redo': 'やり直し',
        'search_tab': '検索',
        'check_syntax': '構文チェック',
        'smart_replace': '特殊文字のスマート置換',
        'view_menu': '表示',
        'font_size': 'フォントサイズ...',
        'hex_dump': '現在のファイルの16進ダンプ...',
        'show_history': '履歴を表示',
        'see_quick_docs': 'クイックドキュメントを表示',
        'edit_custom_cmds': 'カスタムコマンドを編集...',
        'font_submenu': 'フォント',
        'run_menu': '実行',
        'find_doukutsu': 'doukutsu.exeを検索...',
        'test_game': 'テスト（F5）',
        'help_menu': 'ヘルプ',
        'about': 'このソフトについて...',
        'search_label': 'ファイル検索:',
        'clear_btn': 'X',
        'status_ready': '準備完了',
        'open_project_dialog_title': '.cstscプロジェクトを開く',
        'save_project_dialog_title': 'プロジェクトを保存',
        'export_tsc_dialog_title': '.tscファイルを保存',
        'load_folder_title': '.tscファイルのあるフォルダを選択',
        'hex_info': 'データなし',
        'hex_window_title': '16進ダンプ（最初の512バイト）',
        'settings_window_title': '設定',
        'auto_save_label': 'プロジェクトを自動保存（.cstsc）6分ごと',
        'dark_theme_label': 'ダークテーマ',
        'language_label': '言語:',
        'default_font_label': 'デフォルトフォント:',
        'apply_btn': '適用',
        'close_btn': '閉じる',
        'cmd_info_title': '情報',
        'cmd_not_found': 'カーソル位置にTSCコマンドがありません。',
        'cmd_unrecognized': 'コマンド形式が認識できません。',
        'cmd_unknown': '次のコマンドのドキュメントはありません',
        'music_id': '音楽ID',
        'direction': '方向',
        'empty_warning': 'テキストが空です。それでも保存しますか？',
        'overwrite_msg': '上書き',
        'overwrite_question': '上書きしますか？',
        'export_success': 'ファイルは正常に保存されました。',
        'project_saved': 'プロジェクトはUTF-8で保存されました。',
        'load_error': 'ファイルを読み込めませんでした',
        'save_error': '保存できませんでした',
        'search_not_found': 'これ以上見つかりません。',
        'search_back_not_found': '後方に見つかりません。',
        'replace_all_count': ' 件置換しました。',
        'no_file_warning': 'ファイルが読み込まれていません。まず.tscを読み込むか保存してください。',
        'save_before_test': '実行前に変更を保存しますか？',
        'exe_not_found': 'doukutsu.exeが見つかりません',
        'game_launched': 'ゲームを起動しました',
        'lines': '行',
        'chars': '文字',
        'history': '履歴',
        'copy': 'コピー',
        'paste': 'ペースト',
        'cut': 'カット',
        'count_chars': '文字数をカウント',
        'count_chars_face': '文字数をカウント（顔あり）',
        'count_normal_title': '文字数カウント（通常）',
        'count_face_title': '文字数カウント（顔）',
        'fits': 'このメッセージはダイアログボックスに正しく収まります',
        'not_fits': 'このメッセージはダイアログボックスに収まらない可能性があります',
        'limit': '制限',
        'quick_docs': 'クイックドキュメント',
        'command': 'コマンド',
        'syntax': '構文',
        'description': '説明',
        'details': 'スクリプト詳細',
        'face_name': '顔',
        'music_name': '音楽',
        'confirm': '確認',
        'backup_warning': '続行する前にこのTSCファイルのバックアップを作成することをお勧めします。\nこの操作は元に戻せません（元に戻す機能を除く）。',
        'done': '完了',
        'no_changes': '変更なし',
        'smart_replace_title': '特殊文字のスマート置換',
        'option_nn': "'ñÑ' を 'nN' に置換",
        'option_accents': 'アクセント記号を削除 (áéíóúüÁÉÍÓÚÜ) → aeiouuAEIOUU',
        'option_symbols': 'まれな記号を削除 (¡¿)',
        'option_all': 'すべて選択',
        'syntax_errors': '構文エラー',
        'syntax_errors_found': '構文エラーが見つかりました。それでも保存しますか？',
        'syntax_no_errors': '構文エラーは見つかりませんでした。',
        'syntax_error_window_title': '構文チェック',
        'auto_save_notification': 'プロジェクトを自動保存しました',
        'find': '検索',
        'replace': '置換',
        'replace_all': 'すべて置換',
        'find_next': '次を検索',
        'find_prev': '前を検索',
        'case_sensitive': '大文字小文字を区別',
        'whole_word': '単語単位',
        'search_term': '検索語:',
        'replace_term': '置換後:',
        'edit_custom_cmds_title': 'カスタムコマンドを編集',
        'custom_cmd_name': 'コマンド名（<なし）:',
        'custom_cmd_desc': '説明:',
        'custom_cmd_args': '引数の数（0-4）:',
        'search_docs': 'コマンドを検索...',
        'tsc_commands': 'コマンド情報を表示',
        'custom_cmd_syntax': 'カスタムコマンド構文...',
        'cmd_syntax_window_title': 'コマンド構文アナライザ',
        'cmd_input_label': 'コマンドライン (例: <CMU0000 または <FAC0001):',
        'parse_button': '分析',
        'syntax_result_title': '分析結果:',
        'syntax_error_purpose': '構文エラーを強制 (無効なコマンド)',
        'clear_button': 'クリア',
        'command_type': 'コマンド',
        'id_type': 'ID',
        'error_type': 'エラー',
        'command_color': '青',
        'id_color': 'ピンク',
        'error_color': '赤',
        'unknown_command': '不明なコマンド',
        'missing_param': 'パラメータ不足',
        'invalid_param': '無効なパラメータ (4桁必要)',
        'extra_text': 'コマンド後の余分なテキスト',
        'command_header': 'コマンド名',
        'id_header': 'ID/パラメータ',
        'error_header': 'エラー説明',
        'customize_command_colors': 'コマンドの色をカスタマイズ...',
        'cmd_colors_title': 'コマンドの色設定',
        'cmd_color_instruction': 'コマンドを選択して色を割り当て:',
        'cmd_list': 'コマンド',
        'current_color': '現在の色',
        'assign_color': '色を割り当て',
        'color_blue': '青 (デフォルト)',
        'color_pink': 'ピンク (ID風)',
        'color_red': '赤 (エラー)',
        'color_reset': 'デフォルトに戻す',
        'unsaved_title': '未保存の変更',
        'unsaved_message': '現在のファイルに未保存の変更があります。\n\n{}を開く前に保存しますか？\n\nはい = 保存して続行\nいいえ = 変更を破棄して続行\nキャンセル = ファイルを変更しない',
        'unsaved_tab_title': '未保存の変更',
        'unsaved_tab_message': '「{}」に未保存の変更があります。\n閉じる前に保存しますか？',
        'face_version_title': 'バージョンを選択',
        'face_version_question': '顔ID {} をどのバージョンで表示しますか？',
        'face_version_freeware': 'フリーウェア',
        'face_version_steam': 'Steam',
        'face_version_cancel': 'キャンセル',
        'face_view_title': '顔を表示',
        'face_view_question': '顔ID {} の画像を表示しますか？\n(後でバージョンを選べます)',
         'ai_assistant': "AIアシスタント",
        'hints': [
            "<FAC01XX>、<FAC10XX>、<FAC11XX> のアニメーション顔は Switch 版限定です。",
            "Switch 版の TSC ファイルはプレーンテキストです。",
            "書きすぎてテキストボックスからはみ出さないように！テキストを選択し、右クリックして文字カウンターを使いましょう。",
            "イベントには # を付けて。ID を整理しましょう。",
            "プロのヒント: キーボードを使いましょう。",
            "ゲームにテキストが表示されない場合、「¿¡」を使っていませんか？右クリックで一括削除。",
            "コメントを入れるときは注意。ゲームは繊細で混乱する可能性があります。",
            "たまには別のエディターも使いましょう。",
            "プロのヒント: マウスやタッチパッドを使いましょう。",
            "TSC のバックアップを取ってください。一歩間違えるとゲームがクラッシュします。",
            "編集する前に設定が必要です。",
            "F5 を押すと素早くテストできます。",
            "TSC プログラミング言語はとてもシンプルで冗談のように思えますが、決して簡単ではありません。",
            "コマンドが何をするのか分からず、ドキュメントを見るのが面倒ですか？右クリックで概要を表示。",
            "TSC が「hhxxjxnjxb#=hh+¨shswhh」のように開く場合、暗号を変更すれば読めるようになります。"
        ]
    }
}

def get_language(lang_code: str) -> dict:
    """Return the dictionary for the given language code."""
    return LANGS.get(lang_code, LANGS['en'])