# -*- coding: utf-8 -*-
"""
Language dictionaries for TSC Editor+.
"""

LANGS = {
    'en': {
        'window_title': 'TSC Editor+',
        'file_menu': 'File',
        'open_tsc': 'Open .tsc...',
        'open_project': 'Open .cstsc project...',
        'open_folder': 'Open project folder...',
        'delete_from_list': 'Delete loaded TSC from this list',
        'delete_all_from_list': 'Delete all TSCs from this list',
        'export_tsc': 'Export .tsc...',
        'save_project': 'Save project .cstsc...',
        'settings': 'Settings...',
        'exit': 'Exit',
        'edit_menu': 'Edit',
        'undo': 'Undo',
        'redo': 'Redo',
        'search_tab': 'Search',
        'check_syntax': 'Check Syntax',
        'smart_replace': 'Smart Replace Special Characters',
        'view_menu': 'View',
        'font_size': 'Font size...',
        'hex_dump': 'Hex dump of current file...',
        'show_history': 'Show History',
        'see_quick_docs': 'See Quick Docs',
        'edit_custom_cmds': 'Edit Custom Commands...',
        'font_submenu': 'Font',
        'run_menu': 'Run',
        'find_doukutsu': 'Find doukutsu.exe...',
        'test_game': 'Test (F5)',
        'help_menu': 'Help',
        'about': 'About...',
        'search_label': 'Search file:',
        'clear_btn': 'X',
        'status_ready': 'Ready',
        'open_project_dialog_title': 'Open .cstsc project',
        'save_project_dialog_title': 'Save project',
        'export_tsc_dialog_title': 'Save .tsc file',
        'load_folder_title': 'Select folder with .tsc files',
        'hex_info': 'No data',
        'hex_window_title': 'Hex dump (first 512 bytes)',
        'settings_window_title': 'Settings',
        'auto_save_label': 'Auto-save project (.cstsc) every 6 minutes',
        'dark_theme_label': 'Dark theme',
        'language_label': 'Language:',
        'default_font_label': 'Default font:',
        'apply_btn': 'Apply',
        'close_btn': 'Close',
        'cmd_info_title': 'Info',
        'cmd_not_found': 'No TSC command at cursor.',
        'cmd_unrecognized': 'Command format not recognized.',
        'cmd_unknown': 'No documentation for',
        'music_id': 'Music ID',
        'direction': 'Direction',
        'empty_warning': 'The text is empty. Save anyway?',
        'overwrite_msg': 'Overwrite',
        'overwrite_question': 'Overwrite',
        'export_success': 'File saved successfully.',
        'project_saved': 'Project saved in UTF-8.',
        'load_error': 'Could not load file',
        'save_error': 'Could not save file',
        'search_not_found': 'No more matches found.',
        'search_back_not_found': 'No more matches backwards.',
        'replace_all_count': ' replacements performed.',
        'no_file_warning': 'No file loaded. Load or save a .tsc first.',
        'save_before_test': 'Save changes before running?',
        'exe_not_found': 'Could not find doukutsu.exe',
        'game_launched': 'Game launched',
        'lines': 'Lines',
        'chars': 'Chars',
        'history': 'History',
        'copy': 'Copy',
        'paste': 'Paste',
        'cut': 'Cut',
        'count_chars': 'Count Characters',
        'count_chars_face': 'Count Characters (Face)',
        'count_normal_title': 'Character count (Normal)',
        'count_face_title': 'Character count (Face)',
        'fits': 'This text fits correctly in the message box',
        'not_fits': 'This text may NOT fit correctly in the message box',
        'limit': 'Limit',
        'quick_docs': 'Quick Docs',
        'command': 'Command',
        'syntax': 'Syntax',
        'description': 'Description',
        'details': 'Script Details',
        'face_name': 'Face',
        'music_name': 'Music',
        'confirm': 'Confirm',
        'backup_warning': 'It is recommended to make a backup of this TSC file before proceeding.\nThis action cannot be undone (except via Undo).',
        'done': 'Done',
        'no_changes': 'No changes',
        'smart_replace_title': 'Smart Replace Special Characters',
        'option_nn': "Replace 'ñÑ' with 'nN'",
        'option_accents': 'Remove accents (áéíóúüÁÉÍÓÚÜ) → aeiouuAEIOUU',
        'option_symbols': 'Remove rare symbols (¡¿)',
        'option_all': 'All of the above',
        'syntax_errors': 'Syntax Errors',
        'syntax_errors_found': 'Syntax errors found. Save anyway?',
        'syntax_no_errors': 'No syntax errors found.',
        'syntax_error_window_title': 'Syntax Check',
        'auto_save_notification': 'Project auto-saved',
        'find': 'Find',
        'replace': 'Replace',
        'replace_all': 'Replace All',
        'find_next': 'Find Next',
        'find_prev': 'Find Previous',
        'case_sensitive': 'Case sensitive',
        'whole_word': 'Whole word',
        'search_term': 'Search term:',
        'replace_term': 'Replace with:',
        'edit_custom_cmds_title': 'Edit Custom Commands',
        'custom_cmd_name': 'Command name (without <):',
        'custom_cmd_desc': 'Description:',
        'custom_cmd_args': 'Number of arguments (0-4):',
        'search_docs': 'Search command...',
        'tsc_commands': 'Show command info',
        'custom_cmd_syntax': 'Custom Command Syntax...',
        'cmd_syntax_window_title': 'Command Syntax Analyzer',
        'cmd_input_label': 'Command line (e.g. <CMU0000 or <FAC0001):',
        'parse_button': 'Analyze',
        'syntax_result_title': 'Analysis result:',
        'syntax_error_purpose': 'Force syntax error (invalid command)',
        'clear_button': 'Clear',
        'command_type': 'Command',
        'id_type': 'ID',
        'error_type': 'Error',
        'command_color': 'Blue',
        'id_color': 'Pink',
        'error_color': 'Red',
        'unknown_command': 'Unknown command',
        'missing_param': 'Missing parameter',
        'invalid_param': 'Invalid parameter (must be 4 digits)',
        'extra_text': 'Extra text after command',
        'command_header': 'Command name',
        'id_header': 'ID/Parameter',
        'error_header': 'Error description',
        'customize_command_colors': 'Customize Command Colors...',
        'cmd_colors_title': 'Command Color Customization',
        'cmd_color_instruction': 'Select a command and assign a color:',
        'cmd_list': 'Command',
        'current_color': 'Current Color',
        'assign_color': 'Assign Color',
        'color_blue': 'Blue (default)',
        'color_pink': 'Pink (like ID)',
        'color_red': 'Red (error)',
        'color_reset': 'Reset to default',
        'unsaved_title': 'Unsaved Changes',
        'unsaved_message': 'There are unsaved changes in the current file.\n\nDo you want to save them before opening {}?\n\nYes = Save and continue\nNo = Discard changes and continue\nCancel = Do not change file',
        'unsaved_tab_title': 'Unsaved Changes',
        'unsaved_tab_message': 'There are unsaved changes in "{}".\nDo you want to save them before closing?',
        'face_version_title': 'Select version',
        'face_version_question': 'Show face ID {} from which version?',
        'face_version_freeware': 'Freeware',
        'face_version_steam': 'Steam',
        'face_version_cancel': 'Cancel',
        'face_view_title': 'Show face',
        'face_view_question': 'Show face image for ID {}?\n(You can choose version later)',
        'ai_assistant': "AI Assistant",
        'hints': [
            "Did you know that animated faces <FAC01XX>, <FAC10XX>, <FAC11XX> are exclusive to Switch?",
            "Did you know that TSC files on Switch are plain text?",
            "Be careful not to write too much or you'll exceed the text box! Select your text, right-click and use the character counter.",
            "Place an event with #. Remember, stay organized with IDs.",
            "Pro tip: Use the keyboard.",
            "Your text not showing in-game? Maybe you used '¿¡'. Right-click and remove those characters with one click.",
            "Be careful when putting comments in these files; the game is touchy and may get confused.",
            "Use another editor every now and then.",
            "Pro tip: Use the mouse or touchpad.",
            "Backup your TSC files; one wrong step and the game crashes.",
            "Before editing, you must configure.",
            "Press F5 to test quickly.",
            "TSC programming language is so simple it's almost a joke (but don't think it's a piece of cake).",
            "Don't know what a command does and too lazy to check docs? Right-click and see a summary.",
            "If your TSC opens as 'hhxxjxnjxb#=hh+¨shswhh', change the cipher and you'll be able to read it."
        ],
        'backup_title': 'Backup',
        'backup_no_current': 'No .tsc file is currently loaded.',
        'backup_created': 'Backup created:',
        'backup_error': 'Error',
        'backup_failed': 'Could not create backup:',
        'backup_no_files': 'No .tsc files in the list.\nLoad a folder first (Ctrl+Shift+Alt+O).',
        'backup_progress_title': 'Backup in progress',
        'backup_copying': 'Copying files...',
        'backup_completed': 'Backup completed.',
        'backup_files_copied': 'Files copied: {}/{}',
        'backup_errors': 'Errors: {}',
        'backup_directory_label': 'Backup directory:',
        'backup_directory_help': 'If set, backups will be saved inside this folder (in dated subfolders).\nIf empty, backups are saved next to each file/project.',
        'smart_replace_confirm_title': 'Confirm mass replacement',
        'smart_replace_confirm_msg': 'Smart character replacement will be applied to {} .tsc file(s).\n\nReplacements:\n- "ñÑ" → "nN"\n- Accents (áéíóúü) → unaccented letters\n- Symbols ¡¿ → removed\n\nDo you want to continue? It is recommended to make a backup first.',
        'smart_replace_processing': 'Processing files...',
        'smart_replace_replacing': 'Replacing special characters...',
        'smart_replace_completed': 'Process completed',
        'smart_replace_result': 'Files processed: {}\nModified: {}\nErrors: {}',
        'browse_button': 'Browse...',
        'clear_button': 'Clear',
        'backup_created_log': 'Backup created: {}',
        'backup_all_log': 'Backup all TSC: {} files copied to {}',
        'smart_replace_no_files': 'No .tsc files in the list. Load a folder first.',
        'smart_replace_log': 'Smart replace applied to {}',
        'export_txt_success': 'File saved as plain text (UTF-8).',
        'delete_confirm_title': 'Confirm',
        'delete_confirm_current': 'Delete current file from list?',
        'delete_confirm_all': 'Delete ALL files from the sidebar list?\n(They will NOT be deleted from the disk)',
        'keep_recent_label': 'Keep recent TSC folder on startup',
        'theme_label': 'Theme:',
        'load_mode_label': 'TSC file loading mode:',
        'load_mode_auto': 'Always auto-detect',
        'load_mode_ask': 'Always ask per file',
        'load_mode_manual': 'Always use this encoding and cipher',
        'encoding_label': 'Encoding:',
        'cipher_label': 'Cipher:',
        'export_mode_label': 'TSC file export mode:',
        'export_mode_auto': 'Auto (use encoding & cipher from opened file)',
        'export_mode_select': 'Ask per export',
        'export_mode_manual': 'Always use this encoding and cipher',
        'another_tsc': 'another .tsc file',
        'another_project': 'another .cstsc project',
        'another_folder': 'a project folder',
        'history_saved_tsc': 'Saved TSC: {}',
        'history_exported_txt': 'Exported as plain text: {}',
        'history_saved_project': 'Saved project: {}',
        'history_opened_project': 'Opened project: {}',
        'history_removed_file': 'Removed current file from list',
        'history_cleared_list': 'Cleared all files from list',
        'history_auto_corrected': 'Auto-corrected encoding from {} to {} (suspicious chars)',
        'backup_copying_file': 'Copying: {}',
        'no_file_loaded': 'No file is currently loaded.',
        'load_error_msg': 'Could not load {}:\n{}',
        'history_editor_started': 'Editor started',
        'status_loaded': 'Loaded: {} | Cipher={}, Enc={}',
        'history_opened_tsc': 'Opened TSC: {} (cipher={}, enc={})',
        'noto_sans_jp_desc': 'Noto Sans JP (Use only for Japanese TSC)',
        'export_status_tsc': 'Exported: {} | Cipher: {}',
        'export_status_txt': 'Exported as plain text: {}',
        'history_saved_tsc': 'Saved TSC: {}',
        'history_exported_txt': 'Exported as plain text: {}',
        'export_success_cipher': 'File saved successfully.\nCipher: {}',
        'status_project_saved': 'Project saved: {}',
        'status_project_loaded': 'Project loaded: {}',
        'unsaved_delete_current': 'delete this file from the list',
        'unsaved_delete_all': 'delete all files from the list',
        'status_file_removed': 'File removed from list.',
        'status_list_cleared': 'List cleared.',
        'history_removed_file': 'Removed current file from list',
        'history_cleared_list': 'Cleared all files from list',
        'custom_cmds_title': 'Edit Custom Commands',
        'custom_cmds_command': 'Command',
        'custom_cmds_args': 'Args',
        'custom_cmds_desc': 'Description',
        'custom_cmds_add': 'Add',
        'custom_cmds_edit': 'Edit',
        'custom_cmds_remove': 'Remove',
        'custom_cmds_error_title': 'Error',
        'custom_cmds_name_length': 'Command name must be 2-3 letters.',
        'custom_cmds_already_exists': 'Command already exists.',
        'custom_cmds_add_title': 'Add Command',
        'custom_cmds_edit_title': 'Edit Command',
        'custom_cmds_arguments_title': 'Arguments',
        'custom_cmds_description_title': 'Description',        
        'cmd_syntax_error_prefix': 'Error',
        'cmd_syntax_extra_text': 'Extra text after command (expected {})',
        'cmd_syntax_none': 'none',
        'cmd_syntax_missing_param': 'Missing parameter (expected {})',
        'suggest_title': 'Suggest',
        'suggest_no_file': 'No file open to analyze.',
        'suggest_encoding_found': 'Suggested encoding: {}',
        'suggest_no_encoding': 'Could not determine encoding.',
        'suggest_button': 'Suggest',
        'backup_select_folder_title': 'Select backup folder',
        'history_undo': 'Undo',
        'history_redo': 'Redo',
        'history_copied': 'Copied',
        'history_pasted': 'Pasted',
        'history_cut': 'Cut',
        'history_backspace': 'Backspace',
        'history_enter': 'Enter',
        'history_space': 'Space',
        'history_handwrite': 'Handwrite',
        'count_no_selection': 'No text selected.',
        'count_empty_selection': 'Selected text is empty.',
        'count_chars_label': 'Characters: {}',
        'count_limit_label': 'Limit: {}',
        'face_version_switch': 'Switch (Animated)',

        # ABOUT
        'about_text': """TSC Editor+ v2.1
        Professional editor for Cave Story .tsc files
        Encryption compatible with Booster's Lab (Carrot Lord)

        Features:
        - Syntax highlighting (commands, events, numbers, special characters)
        - Customizable command colors (blue/pink/red)
        - Action history, line and character counter
        - Search and replace with real-time highlighting
        - Quick command documentation with integrated search
        - Customizable commands (add/edit/delete)
        - Auto-save every 6 minutes
        - Quick font size change with Ctrl+Wheel
        - Dark mode with dark title bar and full interface
        - Multilingual support (Spanish, English, Japanese)
        - Command Syntax Analysis window (Ctrl+Shift+C)
        - Modern tabs (Ctrl+T new tab, Ctrl+W close tab)
        - Keep recent TSC folder on startup
        - Face image preview for <FAC> command (Freeware/Steam/Switch)
        - Export to .txt as plain text (UTF-8)
        - Backup current TSC (Ctrl+B) and all TSC (Ctrl+Shift+B)
        - Smart Replace All TSC (batch replace special characters)

        Shortcuts: Ctrl+O, Ctrl+S, Ctrl+Shift+S, Ctrl+Z, Ctrl+Y, Ctrl+F, Ctrl+H, Ctrl+R, Ctrl+K, F5, Ctrl+Del, Ctrl+Shift+Del, Ctrl+Shift+C, Ctrl+T, Ctrl+W, Ctrl+Shift+W, Ctrl+Alt+W, Ctrl+N, Ctrl+B, Ctrl+Shift+B, Alt+F4

        Created for the Cave Story modding community.""",

        'backup_current_tsc': 'Backup Current TSC',
        'backup_all_tsc': 'Backup All TSC',
        'smart_replace_all_tsc': 'Smart Replace All TSC Files',
        'toggle_theme': 'Toggle Theme (Darkly/Cosmo)',
        'font_size_title': 'Font Size',
        'font_size_label': 'Font size:',
        'tab_close': 'Close',
        'tab_close_others': 'Close Others',
        'tab_close_all': 'Close All',
        'new_file_title': 'New File {}',
        'history_new_empty_tab': 'New empty tab: {}',
    },
    'es': {
        'window_title': 'TSC Editor+',
        'file_menu': 'Archivo',
        'open_tsc': 'Abrir .tsc...',
        'open_project': 'Abrir proyecto .cstsc...',
        'open_folder': 'Abrir carpeta de proyectos...',
        'delete_from_list': 'Eliminar TSC cargado de esta lista',
        'delete_all_from_list': 'Eliminar todos los TSC de esta lista',
        'export_tsc': 'Exportar .tsc...',
        'save_project': 'Guardar proyecto .cstsc...',
        'settings': 'Configuración...',
        'exit': 'Salir',
        'edit_menu': 'Editar',
        'undo': 'Deshacer',
        'redo': 'Rehacer',
        'search_tab': 'Buscar',
        'check_syntax': 'Verificar sintaxis',
        'smart_replace': 'Reemplazo inteligente de caracteres especiales',
        'view_menu': 'Ver',
        'font_size': 'Tamaño de fuente...',
        'hex_dump': 'Ver hexadecimal del archivo actual...',
        'show_history': 'Mostrar historial',
        'see_quick_docs': 'Ver documentación rápida',
        'edit_custom_cmds': 'Editar comandos personalizados...',
        'font_submenu': 'Fuente',
        'run_menu': 'Ejecutar',
        'find_doukutsu': 'Buscar doukutsu.exe...',
        'test_game': 'Probar (F5)',
        'help_menu': 'Ayuda',
        'about': 'Acerca de...',
        'search_label': 'Buscar archivo:',
        'clear_btn': 'X',
        'status_ready': 'Listo',
        'open_project_dialog_title': 'Abrir proyecto .cstsc',
        'save_project_dialog_title': 'Guardar proyecto',
        'export_tsc_dialog_title': 'Guardar archivo .tsc',
        'load_folder_title': 'Seleccionar carpeta con archivos .tsc',
        'hex_info': 'Sin datos',
        'hex_window_title': 'Vista hexadecimal (primeros 512 bytes)',
        'settings_window_title': 'Configuración',
        'auto_save_label': 'Auto-guardar proyecto (.cstsc) cada 6 minutos',
        'dark_theme_label': 'Tema oscuro',
        'language_label': 'Idioma:',
        'default_font_label': 'Fuente predeterminada:',
        'apply_btn': 'Aplicar',
        'close_btn': 'Cerrar',
        'cmd_info_title': 'Información',
        'cmd_not_found': 'No hay un comando TSC en esta posición.',
        'cmd_unrecognized': 'Formato de comando no reconocido.',
        'cmd_unknown': 'No hay documentación para',
        'music_id': 'ID de música',
        'direction': 'Dirección',
        'empty_warning': 'El texto está vacío. ¿Guardar de todos modos?',
        'overwrite_msg': 'Sobrescribir',
        'overwrite_question': '¿Sobrescribir',
        'export_success': 'Archivo guardado correctamente.',
        'project_saved': 'Proyecto guardado en UTF-8.',
        'load_error': 'No se pudo cargar el archivo',
        'save_error': 'No se pudo guardar',
        'search_not_found': 'No se encontró más texto.',
        'search_back_not_found': 'No se encontró texto hacia atrás.',
        'replace_all_count': ' reemplazos realizados.',
        'no_file_warning': 'No hay archivo cargado. Cargue o guarde un .tsc primero.',
        'save_before_test': '¿Guardar cambios antes de ejecutar?',
        'exe_not_found': 'No se encontró doukutsu.exe',
        'game_launched': 'Juego lanzado',
        'lines': 'Líneas',
        'chars': 'Caracteres',
        'history': 'Historial',
        'copy': 'Copiar',
        'paste': 'Pegar',
        'cut': 'Cortar',
        'count_chars': 'Contar caracteres',
        'count_chars_face': 'Contar caracteres (cara)',
        'count_normal_title': 'Conteo de caracteres (Normal)',
        'count_face_title': 'Conteo de caracteres (Cara)',
        'fits': 'Este mensaje puede caber correctamente en la caja de diálogo',
        'not_fits': 'Este mensaje quizá NO pueda caber correctamente en la caja de diálogo',
        'limit': 'Límite',
        'quick_docs': 'Documentación rápida',
        'command': 'Comando',
        'syntax': 'Sintaxis',
        'description': 'Descripción',
        'details': 'Detalles del script',
        'face_name': 'Cara',
        'music_name': 'Música',
        'confirm': 'Confirmar',
        'backup_warning': 'Se recomienda hacer una copia de seguridad de este archivo TSC antes de continuar.\nEsta acción no se puede deshacer (excepto mediante Deshacer).',
        'done': 'Hecho',
        'no_changes': 'Sin cambios',
        'smart_replace_title': 'Reemplazo inteligente de caracteres especiales',
        'option_nn': "Reemplazar 'ñÑ' por 'nN'",
        'option_accents': 'Eliminar acentos (áéíóúüÁÉÍÓÚÜ) → aeiouuAEIOUU',
        'option_symbols': 'Eliminar símbolos raros (¡¿)',
        'option_all': 'Todo lo anterior',
        'syntax_errors': 'Errores de sintaxis',
        'syntax_errors_found': 'Se encontraron errores de sintaxis. ¿Guardar de todos modos?',
        'syntax_no_errors': 'No se encontraron errores de sintaxis.',
        'syntax_error_window_title': 'Verificación de sintaxis',
        'auto_save_notification': 'Proyecto auto-guardado',
        'find': 'Buscar',
        'replace': 'Reemplazar',
        'replace_all': 'Reemplazar todo',
        'find_next': 'Buscar siguiente',
        'find_prev': 'Buscar anterior',
        'case_sensitive': 'Mayúsculas/minúsculas',
        'whole_word': 'Palabra completa',
        'search_term': 'Término a buscar:',
        'replace_term': 'Reemplazar con:',
        'edit_custom_cmds_title': 'Editar comandos personalizados',
        'custom_cmd_name': 'Nombre del comando (sin <):',
        'custom_cmd_desc': 'Descripción:',
        'custom_cmd_args': 'Número de argumentos (0-4):',
        'search_docs': 'Buscar comando...',
        'tsc_commands': 'Mostrar información del comando',
        'custom_cmd_syntax': 'Sintaxis de comando personalizado...',
        'cmd_syntax_window_title': 'Analizador de sintaxis de comandos',
        'cmd_input_label': 'Línea de comando (ej. <CMU0000 o <FAC0001):',
        'parse_button': 'Analizar',
        'syntax_result_title': 'Resultado del análisis:',
        'syntax_error_purpose': 'Forzar error de sintaxis (comando inválido)',
        'clear_button': 'Limpiar',
        'command_type': 'Comando',
        'id_type': 'ID',
        'error_type': 'Error',
        'command_color': 'Azul',
        'id_color': 'Rosa',
        'error_color': 'Rojo',
        'unknown_command': 'Comando desconocido',
        'missing_param': 'Parámetro faltante',
        'invalid_param': 'Parámetro inválido (deben ser 4 dígitos)',
        'extra_text': 'Texto extra después del comando',
        'command_header': 'Nombre del comando',
        'id_header': 'ID/Parámetro',
        'error_header': 'Descripción del error',
        'customize_command_colors': 'Personalizar colores de comandos...',
        'cmd_colors_title': 'Personalización de colores de comandos',
        'cmd_color_instruction': 'Selecciona un comando y asígnale un color:',
        'cmd_list': 'Comando',
        'current_color': 'Color actual',
        'assign_color': 'Asignar color',
        'color_blue': 'Azul (por defecto)',
        'color_pink': 'Rosa (como ID)',
        'color_red': 'Rojo (error)',
        'color_reset': 'Restablecer a por defecto',
        'unsaved_title': 'Cambios sin guardar',
        'unsaved_message': 'Hay cambios sin guardar en el archivo actual.\n\n¿Desea guardarlos antes de abrir {}?\n\nSí = Guardar y continuar\nNo = Descartar cambios y continuar\nCancelar = No cambiar de archivo',
        'unsaved_tab_title': 'Cambios sin guardar',
        'unsaved_tab_message': 'Hay cambios sin guardar en "{}".\n¿Desea guardarlos antes de cerrar?',
        'face_version_title': 'Seleccionar versión',
        'face_version_question': '¿Mostrar cara ID {} de qué versión?',
        'face_version_freeware': 'Freeware',
        'face_version_steam': 'Steam',
        'face_version_cancel': 'Cancelar',
        'face_view_title': 'Ver cara',
        'face_view_question': '¿Mostrar imagen de la cara {}?\n(Puedes elegir versión después)',
        'ai_assistant': "Asistente IA",
        'hints': [
            "¿Sabías que las caras animadas <FAC01XX>, <FAC10XX>, <FAC11XX> son exclusivas de Switch?",
            "¿Sabías que los TSC en Switch son solo texto plano?",
            "¡Ten cuidado escribiendo de más o te saldrás de la caja de texto! Selecciona tu texto, haz clic derecho y usa el contador de caracteres.",
            "Coloca un evento con #. Recuerda, sé organizado con los IDs.",
            "Pro tip: Usa el teclado.",
            "Tu texto no se muestra en el juego, posiblemente usaste '¿¡'. Haz clic derecho y elimina esos caracteres con un clic.",
            "Ten cuidado al poner comentarios en estos archivos; el juego es malpensado y se puede confundir.",
            "Usa otro editor de vez en cuando.",
            "Pro tip: Usa el mouse o touchpad.",
            "Haz respaldos de tus TSC; un paso en falso y el juego explota.",
            "Antes de editar, debes configurar.",
            "Pulsa F5 para testear rápidamente.",
            "El lenguaje de programación TSC es tan sencillo que parece chiste (pero no te creas que es pan comido).",
            "¿No sabes qué hace X comando y te da flojera ir a la documentación? Haz clic derecho y verás un resumen de ello.",
            "Si tu TSC abre así 'hhxxjxnjxb#=hh+¨shswhh', cambia el cifrado y podrás leerlo."
        ],
        'backup_title': 'Respaldo',
        'backup_no_current': 'No hay un archivo .tsc cargado actualmente.',
        'backup_created': 'Respaldo creado:',
        'backup_error': 'Error',
        'backup_failed': 'No se pudo crear el respaldo:',
        'backup_no_files': 'No hay archivos .tsc en la lista.\nCarga una carpeta primero (Ctrl+Shift+Alt+O).',
        'backup_progress_title': 'Respaldo en progreso',
        'backup_copying': 'Copiando archivos...',
        'backup_completed': 'Respaldo completado.',
        'backup_files_copied': 'Archivos copiados: {}/{}',
        'backup_errors': 'Errores: {}',
        'backup_directory_label': 'Directorio de respaldo:',
        'backup_directory_help': 'Si se establece, los respaldos se guardarán dentro de esta carpeta (en subcarpetas con fecha).\nSi está vacío, los respaldos se guardan junto a cada archivo/proyecto.',
        'smart_replace_confirm_title': 'Confirmar reemplazo masivo',
        'smart_replace_confirm_msg': 'Se aplicará reemplazo inteligente de caracteres especiales a {} archivo(s) .tsc.\n\nReemplazos:\n- "ñÑ" → "nN"\n- Acentos (áéíóúü) → letras sin acentuar\n- Símbolos ¡¿ → eliminados\n\n¿Deseas continuar? Se recomienda hacer una copia de seguridad antes.',
        'smart_replace_processing': 'Procesando archivos...',
        'smart_replace_replacing': 'Reemplazando caracteres especiales...',
        'smart_replace_completed': 'Proceso completado',
        'smart_replace_result': 'Archivos procesados: {}\nModificados: {}\nErrores: {}',
        'browse_button': 'Examinar...',
        'clear_button': 'Limpiar',
        'backup_created_log': 'Backup creado: {}',
        'backup_all_log': 'Backup all TSC: {} archivos copiados a {}',
        'smart_replace_no_files': 'No hay archivos .tsc en la lista. Primero carga una carpeta.',
        'smart_replace_log': 'Smart replace aplicado a {}',
        'export_txt_success': 'Archivo guardado como texto plano (UTF-8).',
        'delete_confirm_title': 'Confirmar',
        'delete_confirm_current': '¿Eliminar el archivo actual de la lista?',
        'delete_confirm_all': '¿Eliminar TODOS los archivos de la lista lateral?\n(NO se eliminarán del disco)',
        'keep_recent_label': 'Mantener carpeta TSC reciente al inicio',
        'theme_label': 'Tema:',
        'load_mode_label': 'Modo de carga de archivos TSC:',
        'load_mode_auto': 'Siempre auto-detectar',
        'load_mode_ask': 'Siempre preguntar por archivo',
        'load_mode_manual': 'Usar siempre esta codificación y cifrado',
        'encoding_label': 'Codificación:',
        'cipher_label': 'Cifrado:',
        'export_mode_label': 'Modo de exportación TSC:',
        'export_mode_auto': 'Auto (usar codificación y cifrado del archivo abierto)',
        'export_mode_select': 'Preguntar por cada exportación',
        'export_mode_manual': 'Usar siempre esta codificación y cifrado',
        'another_tsc': 'otro archivo .tsc',
        'another_project': 'otro proyecto .cstsc',
        'another_folder': 'una carpeta de proyectos',
        'history_saved_tsc': 'TSC guardado: {}',
        'history_exported_txt': 'Exportado como texto plano: {}',
        'history_saved_project': 'Proyecto guardado: {}',
        'history_opened_project': 'Proyecto abierto: {}',
        'history_removed_file': 'Archivo actual eliminado de la lista',
        'history_cleared_list': 'Lista de archivos vaciada',
        'history_auto_corrected': 'Codificación autocorregida de {} a {} (caracteres sospechosos)',
        'backup_copying_file': 'Copiando: {}',
        'no_file_loaded': 'No hay ningún archivo cargado.',
        'load_error_msg': 'No se pudo cargar {}:\n{}',
        'history_editor_started': 'Editor iniciado',
        'status_loaded': 'Cargado: {} | Cifrado={}, Enc={}',
        'history_opened_tsc': 'TSC abierto: {} (cifrado={}, codif={})',
        'noto_sans_jp_desc': 'Noto Sans JP (Solo usar en TSC japoneses)',
        'export_status_tsc': 'Exportado: {} | Cifrado: {}',
        'export_status_txt': 'Exportado como texto plano: {}',
        'history_saved_tsc': 'TSC guardado: {}',
        'history_exported_txt': 'Exportado como texto plano: {}',
        'export_success_cipher': 'Archivo guardado correctamente.\nCifrado: {}',
        'status_project_saved': 'Proyecto guardado: {}',
        'status_project_loaded': 'Proyecto cargado: {}',
        'unsaved_delete_current': 'eliminar este archivo de la lista',
        'unsaved_delete_all': 'eliminar todos los archivos de la lista',
        'status_file_removed': 'Archivo eliminado de la lista.',
        'status_list_cleared': 'Lista vaciada.',
        'history_removed_file': 'Archivo actual eliminado de la lista',
        'history_cleared_list': 'Lista de archivos vaciada',
        'custom_cmds_title': 'Editar comandos personalizados',
        'custom_cmds_command': 'Comando',
        'custom_cmds_args': 'Args',
        'custom_cmds_desc': 'Descripción',
        'custom_cmds_add': 'Agregar',
        'custom_cmds_edit': 'Editar',
        'custom_cmds_remove': 'Eliminar',
        'custom_cmds_error_title': 'Error',
        'custom_cmds_name_length': 'El nombre del comando debe tener 2-3 letras.',
        'custom_cmds_already_exists': 'El comando ya existe.',
        'custom_cmds_add_title': 'Agregar comando',
        'custom_cmds_edit_title': 'Editar comando',
        'custom_cmds_arguments_title': 'Argumentos',
        'custom_cmds_description_title': 'Descripción',
        'cmd_syntax_error_prefix': 'Error',
        'cmd_syntax_extra_text': 'Texto extra después del comando (se esperaban {})',
        'cmd_syntax_none': 'ninguno',
        'cmd_syntax_missing_param': 'Parámetro faltante (se esperaban {})',
        'suggest_title': 'Sugerir',
        'suggest_no_file': 'No hay archivo abierto para analizar.',
        'suggest_encoding_found': 'Codificación sugerida: {}',
        'suggest_no_encoding': 'No se pudo determinar codificación.',
        'suggest_button': 'Sugerir',
        'backup_select_folder_title': 'Seleccionar carpeta de respaldo',
        'history_undo': 'Deshacer',
        'history_redo': 'Rehacer',
        'history_copied': 'Copiado',
        'history_pasted': 'Pegado',
        'history_cut': 'Cortado',
        'history_backspace': 'Retroceso',
        'history_enter': 'Enter',
        'history_space': 'Espacio',
        'history_handwrite': 'Escritura manual',
        'count_no_selection': 'No hay texto seleccionado.',
        'count_empty_selection': 'El texto seleccionado está vacío.',
        'count_chars_label': 'Caracteres: {}',
        'count_limit_label': 'Límite: {}',
        'face_version_switch': 'Switch (Animado)',
        'about_text': """TSC Editor+ v2.1
        Editor profesional para archivos .tsc de Cave Story
        Cifrado compatible con Booster's Lab (Carrot Lord)

        Características:
        - Resaltado de sintaxis (comandos, eventos, números, caracteres especiales)
        - Colores de comandos personalizables (azul/rosa/rojo)
        - Historial de acciones, contador de líneas y caracteres
        - Búsqueda y reemplazo con resaltado en tiempo real
        - Documentación rápida de comandos con búsqueda integrada
        - Comandos personalizables (añadir/editar/eliminar)
        - Auto-guardado cada 6 minutos
        - Cambio rápido de tamaño de fuente con Ctrl+Wheel
        - Modo oscuro con barra de título oscura e interfaz completa
        - Soporte multilenguaje (español, inglés, japonés)
        - Ventana de análisis de sintaxis de comandos (Ctrl+Shift+C)
        - Pestañas modernas (Ctrl+T nueva pestaña, Ctrl+W cerrar pestaña)
        - Mantener carpeta TSC reciente al inicio
        - Vista previa de caras para el comando <FAC> (Freeware/Steam/Switch)
        - Exportar a .txt como texto plano (UTF-8)
        - Respaldo del TSC actual (Ctrl+B) y de todos los TSC (Ctrl+Shift+B)
        - Reemplazo inteligente a todos los TSC (reemplazo masivo de caracteres especiales)

        Atajos: Ctrl+O, Ctrl+S, Ctrl+Shift+S, Ctrl+Z, Ctrl+Y, Ctrl+F, Ctrl+H, Ctrl+R, Ctrl+K, F5, Ctrl+Supr, Ctrl+Mayús+Supr, Ctrl+Mayús+C, Ctrl+T, Ctrl+W, Ctrl+Mayús+W, Ctrl+Alt+W, Ctrl+N, Ctrl+B, Ctrl+Mayús+B, Alt+F4

        Creado para la comunidad de modding de Cave Story.""",
        
        'backup_current_tsc': 'Respaldar TSC actual',
        'backup_all_tsc': 'Respaldar todos los TSC',
        'smart_replace_all_tsc': 'Reemplazo inteligente a todos los TSC',
        'toggle_theme': 'Cambiar tema (Darkly/Cosmo)',
        'font_size_title': 'Tamaño de fuente',
        'font_size_label': 'Tamaño de fuente:',
        'tab_close': 'Cerrar',
        'tab_close_others': 'Cerrar otros',
        'tab_close_all': 'Cerrar todos',
        'new_file_title': 'Archivo nuevo {}',
        'history_new_empty_tab': 'Nueva pestaña vacía: {}',
    },
    'jp': {
        'window_title': 'TSC Editor+',
        'file_menu': 'ファイル',
        'open_tsc': '.tscを開く...',
        'open_project': '.cstscプロジェクトを開く...',
        'open_folder': 'プロジェクトフォルダを開く...',
        'delete_from_list': 'ロードしたTSCをこのリストから削除',
        'delete_all_from_list': 'すべてのTSCをリストから削除',
        'export_tsc': '.tscにエクスポート...',
        'save_project': 'プロジェクトを保存.cstsc...',
        'settings': '設定...',
        'exit': '終了',
        'edit_menu': '編集',
        'undo': '元に戻す',
        'redo': 'やり直し',
        'search_tab': '検索',
        'check_syntax': '構文チェック',
        'smart_replace': '特殊文字のスマート置換',
        'view_menu': '表示',
        'font_size': 'フォントサイズ...',
        'hex_dump': '現在のファイルの16進ダンプ...',
        'show_history': '履歴を表示',
        'see_quick_docs': 'クイックドキュメントを表示',
        'edit_custom_cmds': 'カスタムコマンドを編集...',
        'font_submenu': 'フォント',
        'run_menu': '実行',
        'find_doukutsu': 'doukutsu.exeを検索...',
        'test_game': 'テスト（F5）',
        'help_menu': 'ヘルプ',
        'about': 'このソフトについて...',
        'search_label': 'ファイル検索:',
        'clear_btn': 'X',
        'status_ready': '準備完了',
        'open_project_dialog_title': '.cstscプロジェクトを開く',
        'save_project_dialog_title': 'プロジェクトを保存',
        'export_tsc_dialog_title': '.tscファイルを保存',
        'load_folder_title': '.tscファイルのあるフォルダを選択',
        'hex_info': 'データなし',
        'hex_window_title': '16進ダンプ（最初の512バイト）',
        'settings_window_title': '設定',
        'auto_save_label': 'プロジェクトを自動保存（.cstsc）6分ごと',
        'dark_theme_label': 'ダークテーマ',
        'language_label': '言語:',
        'default_font_label': 'デフォルトフォント:',
        'apply_btn': '適用',
        'close_btn': '閉じる',
        'cmd_info_title': '情報',
        'cmd_not_found': 'カーソル位置にTSCコマンドがありません。',
        'cmd_unrecognized': 'コマンド形式が認識できません。',
        'cmd_unknown': '次のコマンドのドキュメントはありません',
        'music_id': '音楽ID',
        'direction': '方向',
        'empty_warning': 'テキストが空です。それでも保存しますか？',
        'overwrite_msg': '上書き',
        'overwrite_question': '上書きしますか？',
        'export_success': 'ファイルは正常に保存されました。',
        'project_saved': 'プロジェクトはUTF-8で保存されました。',
        'load_error': 'ファイルを読み込めませんでした',
        'save_error': '保存できませんでした',
        'search_not_found': 'これ以上見つかりません。',
        'search_back_not_found': '後方に見つかりません。',
        'replace_all_count': ' 件置換しました。',
        'no_file_warning': 'ファイルが読み込まれていません。まず.tscを読み込むか保存してください。',
        'save_before_test': '実行前に変更を保存しますか？',
        'exe_not_found': 'doukutsu.exeが見つかりません',
        'game_launched': 'ゲームを起動しました',
        'lines': '行',
        'chars': '文字',
        'history': '履歴',
        'copy': 'コピー',
        'paste': 'ペースト',
        'cut': 'カット',
        'count_chars': '文字数をカウント',
        'count_chars_face': '文字数をカウント（顔あり）',
        'count_normal_title': '文字数カウント（通常）',
        'count_face_title': '文字数カウント（顔）',
        'fits': 'このメッセージはダイアログボックスに正しく収まります',
        'not_fits': 'このメッセージはダイアログボックスに収まらない可能性があります',
        'limit': '制限',
        'quick_docs': 'クイックドキュメント',
        'command': 'コマンド',
        'syntax': '構文',
        'description': '説明',
        'details': 'スクリプト詳細',
        'face_name': '顔',
        'music_name': '音楽',
        'confirm': '確認',
        'backup_warning': '続行する前にこのTSCファイルのバックアップを作成することをお勧めします。\nこの操作は元に戻せません（元に戻す機能を除く）。',
        'done': '完了',
        'no_changes': '変更なし',
        'smart_replace_title': '特殊文字のスマート置換',
        'option_nn': "'ñÑ' を 'nN' に置換",
        'option_accents': 'アクセント記号を削除 (áéíóúüÁÉÍÓÚÜ) → aeiouuAEIOUU',
        'option_symbols': 'まれな記号を削除 (¡¿)',
        'option_all': 'すべて選択',
        'syntax_errors': '構文エラー',
        'syntax_errors_found': '構文エラーが見つかりました。それでも保存しますか？',
        'syntax_no_errors': '構文エラーは見つかりませんでした。',
        'syntax_error_window_title': '構文チェック',
        'auto_save_notification': 'プロジェクトを自動保存しました',
        'find': '検索',
        'replace': '置換',
        'replace_all': 'すべて置換',
        'find_next': '次を検索',
        'find_prev': '前を検索',
        'case_sensitive': '大文字小文字を区別',
        'whole_word': '単語単位',
        'search_term': '検索語:',
        'replace_term': '置換後:',
        'edit_custom_cmds_title': 'カスタムコマンドを編集',
        'custom_cmd_name': 'コマンド名（<なし）:',
        'custom_cmd_desc': '説明:',
        'custom_cmd_args': '引数の数（0-4）:',
        'search_docs': 'コマンドを検索...',
        'tsc_commands': 'コマンド情報を表示',
        'custom_cmd_syntax': 'カスタムコマンド構文...',
        'cmd_syntax_window_title': 'コマンド構文アナライザ',
        'cmd_input_label': 'コマンドライン (例: <CMU0000 または <FAC0001):',
        'parse_button': '分析',
        'syntax_result_title': '分析結果:',
        'syntax_error_purpose': '構文エラーを強制 (無効なコマンド)',
        'clear_button': 'クリア',
        'command_type': 'コマンド',
        'id_type': 'ID',
        'error_type': 'エラー',
        'command_color': '青',
        'id_color': 'ピンク',
        'error_color': '赤',
        'unknown_command': '不明なコマンド',
        'missing_param': 'パラメータ不足',
        'invalid_param': '無効なパラメータ (4桁必要)',
        'extra_text': 'コマンド後の余分なテキスト',
        'command_header': 'コマンド名',
        'id_header': 'ID/パラメータ',
        'error_header': 'エラー説明',
        'customize_command_colors': 'コマンドの色をカスタマイズ...',
        'cmd_colors_title': 'コマンドの色設定',
        'cmd_color_instruction': 'コマンドを選択して色を割り当て:',
        'cmd_list': 'コマンド',
        'current_color': '現在の色',
        'assign_color': '色を割り当て',
        'color_blue': '青 (デフォルト)',
        'color_pink': 'ピンク (ID風)',
        'color_red': '赤 (エラー)',
        'color_reset': 'デフォルトに戻す',
        'unsaved_title': '未保存の変更',
        'unsaved_message': '現在のファイルに未保存の変更があります。\n\n{}を開く前に保存しますか？\n\nはい = 保存して続行\nいいえ = 変更を破棄して続行\nキャンセル = ファイルを変更しない',
        'unsaved_tab_title': '未保存の変更',
        'unsaved_tab_message': '「{}」に未保存の変更があります。\n閉じる前に保存しますか？',
        'face_version_title': 'バージョンを選択',
        'face_version_question': '顔ID {} をどのバージョンで表示しますか？',
        'face_version_freeware': 'フリーウェア',
        'face_version_steam': 'Steam',
        'face_version_cancel': 'キャンセル',
        'face_view_title': '顔を表示',
        'face_view_question': '顔ID {} の画像を表示しますか？\n(後でバージョンを選べます)',
        'ai_assistant': "AIアシスタント",
        'hints': [
            "<FAC01XX>、<FAC10XX>、<FAC11XX> のアニメーション顔は Switch 版限定です。",
            "Switch 版の TSC ファイルはプレーンテキストです。",
            "書きすぎてテキストボックスからはみ出さないように！テキストを選択し、右クリックして文字カウンターを使いましょう。",
            "イベントには # を付けて。ID を整理しましょう。",
            "プロのヒント: キーボードを使いましょう。",
            "ゲームにテキストが表示されない場合、「¿¡」を使っていませんか？右クリックで一括削除。",
            "コメントを入れるときは注意。ゲームは繊細で混乱する可能性があります。",
            "たまには別のエディターも使いましょう。",
            "プロのヒント: マウスやタッチパッドを使いましょう。",
            "TSC のバックアップを取ってください。一歩間違えるとゲームがクラッシュします。",
            "編集する前に設定が必要です。",
            "F5 を押すと素早くテストできます。",
            "TSC プログラミング言語はとてもシンプルで冗談のように思えますが、決して簡単ではありません。",
            "コマンドが何をするのか分からず、ドキュメントを見るのが面倒ですか？右クリックで概要を表示。",
            "TSC が「hhxxjxnjxb#=hh+¨shswhh」のように開く場合、暗号を変更すれば読めるようになります。"
        ],
        'backup_title': 'バックアップ',
        'backup_no_current': '現在、.tscファイルが読み込まれていません。',
        'backup_created': 'バックアップを作成しました:',
        'backup_error': 'エラー',
        'backup_failed': 'バックアップを作成できませんでした:',
        'backup_no_files': 'リストに.tscファイルがありません。\n最初にフォルダを読み込んでください（Ctrl+Shift+Alt+O）。',
        'backup_progress_title': 'バックアップ中',
        'backup_copying': 'ファイルをコピーしています...',
        'backup_completed': 'バックアップが完了しました。',
        'backup_files_copied': 'コピーされたファイル: {}/{}',
        'backup_errors': 'エラー: {}',
        'backup_directory_label': 'バックアップディレクトリ:',
        'backup_directory_help': '設定すると、バックアップはこのフォルダ内（日付付きサブフォルダ）に保存されます。\n空の場合は、各ファイル/プロジェクトの隣にバックアップが保存されます。',
        'smart_replace_confirm_title': '一括置換の確認',
        'smart_replace_confirm_msg': '{}個の.tscファイルにスマート文字置換を適用します。\n\n置換内容:\n- "ñÑ" → "nN"\n- アクセント記号（áéíóúü） → アクセントなし\n- 記号 ¡¿ → 削除\n\n続行しますか？事前にバックアップを取ることをお勧めします。',
        'smart_replace_processing': 'ファイルを処理中...',
        'smart_replace_replacing': '特殊文字を置換中...',
        'smart_replace_completed': '処理が完了しました',
        'smart_replace_result': '処理されたファイル: {}\n変更されたファイル: {}\nエラー: {}',
        'browse_button': '参照...',
        'clear_button': 'クリア',
        'backup_created_log': 'バックアップを作成しました: {}',
        'backup_all_log': 'すべてのTSCをバックアップ: {} ファイルを {} にコピーしました',
        'smart_replace_no_files': 'リストに.tscファイルがありません。最初にフォルダを読み込んでください。',
        'smart_replace_log': 'スマート置換を適用しました: {}',
        'export_txt_success': 'プレーンテキスト（UTF-8）として保存しました。',
        'delete_confirm_title': '確認',
        'delete_confirm_current': '現在のファイルをリストから削除しますか？',
        'delete_confirm_all': 'サイドバーのリストから全てのファイルを削除しますか？\n（ディスクからは削除されません）',
        'keep_recent_label': '起動時に最近のTSCフォルダを保持',
        'theme_label': 'テーマ:',
        'load_mode_label': 'TSCファイル読み込みモード:',
        'load_mode_auto': '常に自動検出',
        'load_mode_ask': 'ファイルごとに確認',
        'load_mode_manual': '常にこのエンコーディングと暗号を使用',
        'encoding_label': 'エンコーディング:',
        'cipher_label': '暗号:',
        'export_mode_label': 'TSCエクスポートモード:',
        'export_mode_auto': '自動（開いているファイルのエンコーディングと暗号を使用）',
        'export_mode_select': 'エクスポートごとに確認',
        'export_mode_manual': '常にこのエンコーディングと暗号を使用',
        'another_tsc': '別の.tscファイル',
        'another_project': '別の.cstscプロジェクト',
        'another_folder': 'プロジェクトフォルダ',
        'history_saved_tsc': 'TSCを保存しました: {}',
        'history_exported_txt': 'プレーンテキストとしてエクスポート: {}',
        'history_saved_project': 'プロジェクトを保存しました: {}',
        'history_opened_project': 'プロジェクトを開きました: {}',
        'history_removed_file': '現在のファイルをリストから削除しました',
        'history_cleared_list': 'リストから全ファイルを削除しました',
        'history_auto_corrected': 'エンコーディングを {} から {} に自動修正 (疑わしい文字)',
        'backup_copying_file': 'コピー中: {}',
        'no_file_loaded': 'ファイルが読み込まれていません。',
        'load_error_msg': '{} を読み込めませんでした:\n{}',
        'history_editor_started': 'エディタを起動しました',
        'status_loaded': '読み込み完了: {} | 暗号化={}, エンコード={}',
        'history_opened_tsc': 'TSCを開きました: {} (暗号={}, エンコード={})',
        'noto_sans_jp_desc': 'Noto Sans JP（日本語TSCのみ使用）',
        'status_project_saved': 'プロジェクトを保存しました: {}',
        'status_project_loaded': 'プロジェクトを読み込みました: {}',
        'unsaved_delete_current': 'このファイルをリストから削除',
        'unsaved_delete_all': 'すべてのファイルをリストから削除',
        'status_file_removed': 'ファイルをリストから削除しました。',
        'status_list_cleared': 'リストをクリアしました。',
        'history_removed_file': '現在のファイルをリストから削除しました',
        'history_cleared_list': 'リストから全ファイルを削除しました',
        'custom_cmds_title': 'カスタムコマンドを編集',
        'custom_cmds_command': 'コマンド',
        'custom_cmds_args': '引数',
        'custom_cmds_desc': '説明',
        'custom_cmds_add': '追加',
        'custom_cmds_edit': '編集',
        'custom_cmds_remove': '削除',
        'custom_cmds_error_title': 'エラー',
        'custom_cmds_name_length': 'コマンド名は2～3文字である必要があります。',
        'custom_cmds_already_exists': 'コマンドは既に存在します。',
        'custom_cmds_add_title': 'コマンドを追加',
        'custom_cmds_edit_title': 'コマンドを編集',
        'custom_cmds_arguments_title': '引数',
        'custom_cmds_description_title': '説明',
        'cmd_syntax_error_prefix': 'エラー',
        'cmd_syntax_extra_text': 'コマンド後の余分なテキスト（期待{}）',
        'cmd_syntax_none': 'なし',
        'cmd_syntax_missing_param': 'パラメータ不足（期待{}）',
        'suggest_title': '提案',
        'suggest_no_file': '開いているファイルがありません。',
        'suggest_encoding_found': '提案されたエンコーディング: {}',
        'suggest_no_encoding': 'エンコーディングを判定できませんでした。',
        'suggest_button': '提案',
        'backup_select_folder_title': 'バックアップフォルダを選択',
        'history_undo': '元に戻す',
        'history_redo': 'やり直し',
        'history_copied': 'コピーしました',
        'history_pasted': 'ペーストしました',
        'history_cut': 'カットしました',
        'history_backspace': 'バックスペース',
        'history_enter': 'Enter',
        'history_space': 'スペース',
        'history_handwrite': '手書き入力',
        'count_no_selection': 'テキストが選択されていません。',
        'count_empty_selection': '選択されたテキストは空です。',
        'count_chars_label': '文字数: {}',
        'count_limit_label': '制限: {}',
        'face_version_switch': 'Switch（アニメーション）',
        'about_text': """TSC Editor+ v2.1
        Cave Story .tscファイルのプロフェッショナルエディタ
        Booster's Lab (Carrot Lord) と互換性のある暗号化

        機能:
        - 構文ハイライト（コマンド、イベント、数字、特殊文字）
        - カスタマイズ可能なコマンドの色（青/ピンク/赤）
        - アクション履歴、行数・文字数カウンター
        - リアルタイムハイライト付き検索と置換
        - 統合検索付きクイックコマンドドキュメント
        - カスタマイズ可能なコマンド（追加/編集/削除）
        - 6分ごとの自動保存
        - Ctrl+ホイールで素早くフォントサイズ変更
        - ダークモード（ダークタイトルバーと完全なインターフェース）
        - 多言語サポート（スペイン語、英語、日本語）
        - コマンド構文解析ウィンドウ（Ctrl+Shift+C）
        - モダンなタブ（Ctrl+T 新規タブ、Ctrl+W タブを閉じる）
        - 起動時に最近のTSCフォルダを保持
        - <FAC>コマンドの顔画像プレビュー（Freeware/Steam/Switch）
        - プレーンテキスト（UTF-8）として.txtにエクスポート
        - 現在のTSCのバックアップ（Ctrl+B）および全TSCのバックアップ（Ctrl+Shift+B）
        - 全TSCをスマート置換（特殊文字の一括置換）

        ショートカット: Ctrl+O, Ctrl+S, Ctrl+Shift+S, Ctrl+Z, Ctrl+Y, Ctrl+F, Ctrl+H, Ctrl+R, Ctrl+K, F5, Ctrl+Del, Ctrl+Shift+Del, Ctrl+Shift+C, Ctrl+T, Ctrl+W, Ctrl+Shift+W, Ctrl+Alt+W, Ctrl+N, Ctrl+B, Ctrl+Shift+B, Alt+F4

        Cave Story 改造コミュニティのために作成されました。""",

        'backup_current_tsc': '現在のTSCをバックアップ',
        'backup_all_tsc': 'すべてのTSCをバックアップ',
        'smart_replace_all_tsc': 'すべてのTSCファイルをスマート置換',
        'toggle_theme': 'テーマ切り替え（Darkly/Cosmo）',
        'font_size_title': 'フォントサイズ',
        'font_size_label': 'フォントサイズ:',
        'tab_close': '閉じる',
        'tab_close_others': '他を閉じる',
        'tab_close_all': 'すべて閉じる',
        'new_file_title': '新規ファイル {}',
        'history_new_empty_tab': '新しい空のタブ: {}',
    }
}

def get_language(lang_code: str) -> dict:
    """Return the dictionary for the given language code."""
    return LANGS.get(lang_code, LANGS['en'])
